# fly.toml app configuration file generated for end-mongo-silent-cherry-2522 on 2023-12-31T01:05:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "end-mongo-silent-cherry-2522"
primary_region = "iad"

[build]

[http_service]
  internal_port = 27017
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
