# This is the implicit global project's configuration file, which is only used
# when 'stack' is run outside of a real project. Settings here do _not_ act as
# defaults for all projects. To change Stack's default settings, edit
# '/Users/joebad/Source/end/apps/haskell/src/config.yaml' instead.
#
# For more information about Stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
snapshot: lts-22.32
