app = 'void-site'
primary_region = 'iad'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 3000

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
