app = "void-web"
primary_region = 'iad'

[build]
  image = "nginx:alpine"

[[services]]
  internal_port = 80
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  restart_limit = 0
