name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy api and web
    runs-on: ubuntu-latest
    env:
      WEBSOCKET_URL: ${{ secrets.WEBSOCKET_URL }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_PROD_URL: ${{ secrets.MONGO_PROD_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      NEST_JWT_SECRET: ${{ secrets.NEST_JWT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: haskell-actions/setup@v2

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: yarn install

      - name: Set SHAs for nx affected
        uses: nrwl/nx-set-shas@v3

      - name: Setup fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_WEBSOCKET_URL: ${{ secrets.WEBSOCKET_URL }}
          envkey_MONGO_USER: ${{ secrets.MONGO_USER }}
          envkey_MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          envkey_MONGO_PROD_URL: ${{ secrets.MONGO_PROD_URL }}
          envkey_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          envkey_NEST_JWT_SECRET: ${{ secrets.NEST_JWT_SECRET }}
          envkey_HOST: 0.0.0.0

      - run: git pull --rebase
      - run: yarn deploy
