name: build
on: [pull_request]

jobs:
  build:
    name: Type-check and build all apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: haskell-actions/setup@v2

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Type-check all apps
        uses: borales/actions-yarn@v4
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          cmd: tsc

      - name: Build all apps
        uses: borales/actions-yarn@v4
        with:
          cmd: build
